# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopDongLaoDong',
            fields=[
                ('ma_hd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai_hd', models.CharField(choices=[('FULLTIME', 'Full Time'), ('PARTTIME', 'Part Time')], max_length=20)),
                ('chuc_vu', models.CharField(choices=[('THU_NGAN', 'Thu ngân'), ('QUAN_LY', 'Quản lý'), ('PHUC_VU', 'Phục vụ'), ('PHA_CHE', 'Pha chế')], max_length=20)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('CON_HAN', 'Còn hạn'), ('HET_HAN', 'Hết hạn'), ('DA_HUY', 'Đã hủy')], default='CON_HAN', max_length=20)),
                ('ma_chi_nhanh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong', to='branches.chinhanh')),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong', to='employees.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='HopDongLD_CT',
            fields=[
                ('ma_hd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chi_tiet', serialize=False, to='contracts.hopdonglaodong')),
                ('luong_co_ban', models.FloatField()),
                ('luong_theo_gio', models.FloatField()),
                ('so_gio_lam', models.FloatField()),
                ('che_do_thuong', models.FloatField(default=0)),
                ('phat', models.FloatField(default=0)),
                ('dieu_khoan', models.TextField(blank=True, null=True)),
                ('trach_nhiem', models.TextField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
