# Generated by Django 6.0.3 on 2026-04-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdongld_ct',
            name='phat',
        ),
    ]
