# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='ma_nv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien'),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
