# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCau',
            fields=[
                ('ma_yc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai_yeu_cau', models.CharField(max_length=100)),
                ('ngay_bd', models.DateField()),
                ('ngay_kt', models.DateField()),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(max_length=50)),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
        ),
    ]
