# Generated by Django 6.0.3 on 2026-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('ma_cc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_lam', models.DateField()),
                ('gio_vao', models.TimeField(blank=True, null=True)),
                ('gio_ra', models.TimeField(blank=True, null=True)),
                ('so_gio_lam', models.FloatField(default=0)),
                ('trang_thai', models.CharField(choices=[('DUNG_GIO', 'Đúng giờ'), ('DI_MUON', 'Đi muộn')], default='DUNG_GIO', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
