# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendances', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamcong',
            name='ma_nv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cham_cong', to='employees.nhanvien'),
        ),
    ]
