# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendances', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('ma_bc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_bd', models.DateField()),
                ('ngay_kt', models.DateField()),
                ('ngay_tao', models.DateField()),
                ('tong', models.FloatField()),
                ('ma_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='BaoCao_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nv', models.CharField(max_length=255)),
                ('so_gio_lam', models.FloatField()),
                ('so_ca_lam', models.FloatField()),
                ('di_muon', models.FloatField(default=0)),
                ('ve_som', models.FloatField(default=0)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ma_bc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.baocao')),
                ('ma_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendances.chamcong')),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
            options={
                'unique_together': {('ma_nv', 'ma_cc', 'ma_bc')},
            },
        ),
    ]
