# Generated by Django 6.0.3 on 2026-04-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baocao_ct',
            old_name='ve_som',
            new_name='dung_gio',
        ),
    ]
