# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luong',
            fields=[
                ('ma_luong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('thang', models.IntegerField(default=1)),
                ('nam', models.IntegerField(default=2023)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Đang chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('da_tu_choi', 'Đã từ chối')], default='cho_duyet', max_length=20)),
                ('luong_co_ban', models.FloatField(default=0)),
                ('luong_theo_gio', models.FloatField(default=0)),
                ('so_ca_lam', models.FloatField(default=0)),
                ('so_gio_lam', models.FloatField(default=0)),
                ('thuong', models.FloatField(default=0)),
                ('phat', models.FloatField(default=0)),
                ('tong_luong', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chi_nhanh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.chinhanh')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luongs', to='employees.nhanvien')),
            ],
        ),
    ]
