# Generated by Django 6.0.3 on 2026-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiNhanh',
            fields=[
                ('ma_chi_nhanh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_chi_nhanh', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('sdt', models.CharField(max_length=15)),
            ],
        ),
    ]
