# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã nhân viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('cccd', models.CharField(max_length=12, unique=True, verbose_name='CCCD')),
                ('sdt', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Số điện thoại chỉ được chứa chữ số')], verbose_name='Số điện thoại')),
                ('chuc_vu', models.CharField(choices=[('Thu ngân', 'Thu ngân'), ('Phục vụ', 'Phục vụ'), ('Quản lý', 'Quản lý'), ('Giữ xe', 'Giữ xe'), ('Pha chế', 'Pha chế')], max_length=50, verbose_name='Chức vụ')),
                ('vi_tri_vl', models.CharField(choices=[('Thu ngân', 'Thu ngân'), ('Phục vụ', 'Phục vụ'), ('Quản lý', 'Quản lý'), ('Giữ xe', 'Giữ xe'), ('Pha chế', 'Pha chế')], max_length=50, verbose_name='Vị trí việc làm')),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, null=True, verbose_name='Giới tính')),
                ('tk_ngan_hang', models.CharField(max_length=30, unique=True, verbose_name='Tài khoản ngân hàng')),
                ('ma_chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_viens', to='branches.chinhanh', verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
            },
        ),
    ]
