# Generated by Django 6.0.3 on 2026-04-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='vi_tri_vl',
        ),
    ]
