# Generated by Django 6.0.3 on 2026-04-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('ma_llv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_lam', models.DateField()),
                ('ca_lam', models.CharField(max_length=50)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ngay_tao', models.DateField()),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ma_chi_nhanh', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to='branches.chinhanh')),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to='employees.nhanvien')),
            ],
            options={
                'unique_together': {('ma_llv', 'ma_nv')},
            },
        ),
    ]
